---
- name: Install Chocolatey
  chocolatey.chocolatey.win_chocolatey:
    name:
      - chocolatey
      - chocolatey-core.extension
    state: present
- name: Install Chocolatey Tools
  chocolatey.chocolatey.win_chocolatey:
    name:
      - pebear
      - x64dbg.portable
      - ghidra
      - cutter
      - PeStudio
      - fakenet
      - microsoft-windows-terminal
      - sysinternals
      - 7zip
      - Wireshark
      - die
      - imhex
    state: present
- name: Add Choco to path
  ansible.windows.win_path:
    elements:
      - C:\ProgramData\chocolatey\bin
    state: present
# - name: Enable WMI tracing
#   ansible.windows.win_cmd: Wevtutil.exe sl Microsoft-Windows-WMI-Activity/Trace /e:true /q
