---
- name: Enable IP forwarding for the moment
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes

- name: Enable IP forwarding...permanently
  lineinfile:
    path: /etc/sysctl.conf
    line: 'net.ipv4.ip_forward = 1'

- name: Login Tailscale
  ansible.builtin.command: tailscale up --authkey={{ tailscale_auth_key }} --advertise-routes={{ tailscale_subnet }}
