---
- name: Pull Splunk Docker Image
  community.docker.docker_image:
    name: splunk/splunk
    source: pull

- name: Run Splunk Container
  community.docker.docker_container:
    name: splunk
    image: splunk/splunk
    state: started
    restart: true
    ports:
      - "8000:8000"
      - "9997:9997"
    env:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_PASSWORD: "{{ siem_password }}"
