---
- name: Join Machine to a Domain
  hosts: [zd-fs-01, zd-ws-01]
  gather_facts: true
  tasks:
  - name: Reboot Machine for Rename
    ansible.windows.win_reboot:
      msg: "Rebooting for Provisioning Name Change"
      pre_reboot_delay: 15
  - name: Join to Domain
    ansible.windows.win_domain_membership:
      dns_domain_name: zeroday.local
      hostname: zd-ws-01
      domain_admin_user: Administrator@zeroday.local
      domain_admin_password: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=seclab/data/seclab url=http://127.0.0.1:8200')['seclab_windows_domain_password'] }}"
      state: domain
      register: domain_state
  - name: Reboot Machine
    ansible.windows.win_reboot:
      msg: "Domain joined. Rebooting"
      pre_reboot_delay: 15
    when: domain_state.changed
  roles:
    - rdp
