---
- name: Configure Malware Analysis Machines
  hosts: [malwarelab-victim, malwarelab-analysis]
  vars_prompt:
    - name: siem_ip
      prompt: "Enter SIEM Server IP"
      private: false
    - name: fleet_server_token
      prompt: "Enter Fleet Server Token (Blank for Splunk)"
      private: false
    - name: splunk_password
      prompt: "Enter Splunk Password (Blank for Elastic)"
      private: true
  roles:
    - role: seclab-kali
      when: ansible_facts["distribution"] == "Kali"
      tags: ["Kali"]
    - role: malwarelab-analysis-linux
      become: true
      tags: ["analysis", "linux"]
      when: ansible_facts["distribution"] == "Kali"
    - role: malwarelab-analysis-win
      tags: ["analysis", "windows"]
      when: ansible_facts["os_family"] == "Windows"
    - role: elastic-agent
      tags: ["elastic", "windows"]
      when: ansible_facts["os_family"] == "Windows"
    - role: sysmon
      when: ansible_facts["os_family"] == "Windows"
      tags: ["elastic", "windows"]
    - role: splunk-uf
      tags: ["splunk"]
